services:
  app:
    image: aryfrmnsyh/annotation-it-be:v1
    container_name: anotation_backend
    ports:
      - '3002:3002'
    env_file:
      - .env
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: annotation_mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
